### ISSUE TITLE
Same seed but different address in Daedalus

### ISSUE THREAD

**Issue by Josema** [vacuumlabs/cardanolite#113] opened 2018-07-09 10:58 UTC
Hi, having this seed: `category age design kid snow ketchup give upper toe destroy various concert` 

I got this  address in cardanolite: `DdzFFzCqrht1aN3AUTDGqYyMsSyTJ2ELePqzwc4xruCqjY3MxXDddLb4UFpYWxwHUAGRDkt9ZCGi3HiVKxk8J1wqYs9DcnPXM62zirrS`

But this one in Daedalus: `DdzFFzCqrht9rXNV1cKD8gmVpi1WZa3cGGrm5i5S3XWaiWs8jMR8kMZwx395J5zLYmrE4HnRRQhdAYEUmP5YXvGPYJKWB18uvfsCSiqa`

Is it possible to match the one generated by Daedalus in cardanolite?

**Comment by refi93** [comment] 2018-07-09 11:56
@Josema short answer: Yes, they should be the same, it is a known issue and it will be fixed in the next major release (work in progress on develop branch). But I will elaborate a bit more on that so you won't be misled that CardanoLite and Daedalus always generate the same addresses so below is a more thorough explanation:

First, I would like to clarify how address generation in Daedalus and Cardanolite works:
Cardanolite should generate addresses deterministically from index 0' (first hardened index). Daedalus generates the receive addresses randomly, only the first address happens to be deterministically picked and it should also be 0', but the remaining "receive" addresses you generate in Daedalus are randomly picked and therefore are not reachable from CardanoLite, unless you are "lucky" and Daedalus randomly generates the next receive address and it would have a low derivation index, let's say 2' or 3', which is really a negligible probability. We had to make this trade off (generating addresses deterministically instead of randomly) to make the wallet recoverable online in real time, but since Daedalus during recovery scans the whole blockchain, the CardanoLite wallet is still recoverable in Daedalus (but not vice versa).

I "unpacked" your Daedalus address and I see that you are talking precisely about  the first one you see after creating a new wallet - so yes, it should coincide with the first address in CardanoLite. On the master branch of CardanoLite currently the address generation is shifted by one (caused by a misunderstanding of Daedalus code back then) so that's why they are different now (the CardanoLite you referenced has child index 1'), but in the next major release it will be fixed and you will see the 0' address as the first one in CardanoLite. But it is important to understand that only the first address in CardanoLite and Daedalus will coincide since from that point on the addresses are generated differently in Daedalus and Cardanolite.

Here are some links that may be helpful:
compatibility between CardanoLite and Daedalus -> https://github.com/vacuumlabs/cardanolite/wiki/CardanoLite-FAQ#daedalus-compatibility
how derivation of addresses works: https://cardanodocs.com/technical/hd-wallets/
how addresses are packed and unpacked -> https://cardanodocs.com/cardano/addresses/

**Closed by refi93** 2018-07-09 11:56 UTC
